---
name: Build/Push Development Images
env:
  LC_ALL: "C.UTF-8" # prevent ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
on:
  push:
    branches:
      - devel
      - release_*
      - feature_*
jobs:
  push:
    if: endsWith(github.repository, '/ascender') || startsWith(github.ref, 'refs/heads/release_')
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout ascender
        uses: actions/checkout@v3
        with:
          path: ascender

      - name: Get python version from Makefile
        run: echo py_version=`make PYTHON_VERSION` >> $GITHUB_ENV

      - name: Install python ${{ env.py_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.py_version }}

      - name: Install playbook dependencies
        run: python3 -m pip install docker

      - name: Get latest Ascender tag
        run: echo ascender_tag=`git -c 'versionsort.suffix=-' ls-remote --tags --refs --sort='v:refname' https://github.com/${{ github.repository }}.git  | tail --lines=1  | cut --delimiter='/' --fields=3`

      - name: Build and stage Ascender
        working-directory: ascender
        run: |
          ansible-playbook -v tools/ansible/build.yml \
            -e registry=ghcr.io \
            -e registry_username=${{ github.actor }} \
            -e registry_password=${{ secrets.GITHUB_TOKEN }} \
            -e awx_image=${{ github.repository }}_devel \
            -e awx_version=${{ env.ascender_tag }}+devel \
            -e ansible_python_interpreter=$(which python3) \
            -e push=yes \
            -e awx_official=no
